sudo: false
language: android
jdk: oraclejdk8
env:
  global:
    secure: BJ4ZI+/emJuDPlz27Iaa0JK3vEslCJF8r8Y3Qm1QsPvFKIW4jdmnMiX/bUpTVRYImf69IcCb2LRjMtSbIa2qLa6yZ5GxYOaVAHWhS/dZKWt9Zq0z4lMs9HZ+fXr23gpuch2FHFt06Nm7mtN+4UG0/uboEtRpspca7CbauPiZOnzdeR8lkDG8kat/jCae8WTHrwCZJMERYECPJQD7Js00j0zgdVlquC09LVAdrqIOZTPYYmovCcpvLOieerVRFUC2n40TpUPEYeIKhseioJJrpYMjVhnlfWV/4Zrc7+xiIdjqV+lS9hFtOr8norcvT4ndqG++h7CXAfxDYvceX6vhBMRM8XAfPuo+O51FdUZL/YLlMgc+GbeffDp8XA1cD+XJw5rUnELkIU03i6h4sycwI71WvqPkiiRYzWcn0QsL6A9XfeBZC9Y0trNbGRjX2usZxyuJfXsY7JF7OLLBKCWuvJb210tjHhzhpU1vY53CI0aRx/Ntrf7xGE+EfeK4jULReRKN2ITt01rxx3NaI5iKin6143GAWURChbwnp2qv+SHXz02tAJCtcYOUnlCRpJ0K/6fsZfq/+oYEd/rZ7WB/XzDEIxqKkT9q03Ig4jP3wPN92fApjzrX7WY51MST4CxRs+1C84HHlwyWskNQOCQz42Si5pJv9YgX8Qfio8KNopg=
android:
  components:
  - platform-tools
  - tools
  - build-tools-27.0.0
  - android-26
  - extra-android-m2repository
before_install:
- git clone https://github.com/urho3d/android-ndk.git $HOME/android-ndk
- export ANDROID_NDK_HOME=$HOME/android-ndk
script:
- "./gradlew assemble"
- "./gradlew testDebugUnitTest"
addons:
  coverity_scan:
    project:
      name: brysgo/termux-app
      description: Terminal emulator and Linux environment for Android
    notification_email: brysgo@gmail.com
    build_command_prepend: "./gradlew clean"
    build_command: "./gradlew build"
    branch_pattern: master
deploy:
  provider: releases
  api_key:
    secure: PozGgbkgA7NZmCr3QpObzK+ReDogS5l7J799/iXfU93eDOgOKUGVlD/of/efspbCfXJ3zhiOPD+ShsYw7Yn+DNH5X4X6flQ5cZMGZ4LDxlNgAgS9HXMhG5MRzb67gaJORrEcNtm31dIiBUpRv3O3pH6dwnAf+M3d0mndZUq0cajs0kt9YjAmQDoT2R3+PkL5g7AJBmkNiWIOP8OQjHhFyYzZamAHp3dRfqPpW+HBdiTSDadWDMr7FkpAZMkJ4cDgXbYH29BiEhBDZyH/uRxCsjLf2+YOMtwaRQj0TBA7U/zcmgaEwAdcWqORbkOj5Qr2wngwTgPhuROUEzXYKRqNpdfJqlFBiBUbt52386kWp1U+QdQ5Y0LXDnhaHpgRAjPtnP/IIn8b1d5O4hDOSj5jdepwTGkskgK5Kv22KOPj8daLU9ppC5mZcuOI7uScbozi5bUwVlpKcDw5IYPRv7ADIz9gcdxTNiSOo6tgKIruKP0t08A+KvhgVJGx/UNoM6de+0sRas1Ehctx4ICfsUK+b7Xh7KcmlvZRPKwKD7NdtzCpTsS4yVCoXPEIhRGY43a9z8DZynxyh/UcnEyIa6sSK+jnAV3OoV7W7TdMiTaMJuI0oE6AwphyMI6Yn1O+f0Lkoq7dkf8dibZaDz4Q0lI86MCCPHjBIcbn2NV3EYT3LYE=
  file: app/build/outputs/apk/app-release-unsigned.apk
  skip_cleanup: true
  on:
    repo: brysgo/termux-app
